### ISSUE TITLE
Replace lxml with xml.etree.ElementTree

### ISSUE THREAD

**Issue by amolenaar** [gnome-keysign/babel-glade#3]
Hi,

I noticed this plugins pulls in lxml as a dependency. In my case this is the only place where lxml is used. I'd like to change it to `xml.etree.ElementTree`. As far as I can see the interface is compatible. Would you accept such a change?

**Comment by muelli** [comment]
sure, we're not fixed on lxml.

**Comment by amolenaar** [comment]
Cool. I created #4.

**Comment by satta** [comment]
Hmm, AFAICS there is still a reference to lxml left in `translate.py`...? 
See https://github.com/gnome-keysign/babel-glade/blob/master/babelglade/translate.py#L5

Since I am not familiar enough with the behaviour of the code here, could you probably check if this can simply be replaced by `xml.etree.ElementTree` as well?

**Comment by amolenaar** [comment]
Hi

Ouch! I'll check if it can be replaced by ElementTree too. AFAICS there's nothing lxml specific. I'll add a couple of tests to make sure it works.

**Comment by amolenaar** [comment]
@satta May I ask where and how you use `translate.py`?

**Comment by satta** [comment]
Hi, thanks for having another look! :)
The functionality is used in GNOME Keysign's build/install process, see https://github.com/gnome-keysign/gnome-keysign/blob/master/setup.py#L37.

**Comment by amolenaar** [comment]
@satta Thanks, I can use this as a basis for some test cases.

**Comment by amolenaar** [comment]
It's fixed by #8 (v0.6.1).

**Comment by satta** [comment]
Great, many thanks! 👍
